### ISSUE TITLE
the romanized lyrics aren't showing to me despite being installed properly

### ISSUE THREAD

**Issue by t0kizz** [41pha1/spicetify-extensions#17]
Hi! I don't know why the romanized for korean lyrics are not working despite all extensions being installed. I'll attach the proofs of installation and the error.
![image](https://github.com/41pha1/spicetify-extensions/assets/139022381/6f1de260-2a0a-4128-9ddf-f849598ed58b)
![image](https://github.com/41pha1/spicetify-extensions/assets/139022381/0ba495e3-92fa-4c6c-975c-c44cf72e8caf)
![image](https://github.com/41pha1/spicetify-extensions/assets/139022381/b0f71392-87ba-4d82-aae3-00b1252e5f5e)

**Comment by hamburgerghini1** [comment]
Same problem here

**Comment by antonio-gil** [comment]
Hi,

Due to another issue on my end (#19) I was toying a little bit on my end with the extension, and I think that I have found a workaround for this issue.

Long story short, I had the same issue was you both (@t0kizz , @hamburgerghini1) and while using Spicetify/Spotify devtools I noticed that there was an error on a function that was breaking the exception.

Although this was happening in romaji_lyrics extension, I have taken a look at the romaja_lyrics extension and the faulty function declared in the same way in both extensions, so it's more likely to be failing in same way.

The workaround for this would be, on the JavaScript file, to comment all the addControlUI() function, this is located in line 35, and end on line 47. You can check [here](https://github.com/41pha1/spicetify-extensions/blob/e100b877408539fcaa4f8c7572c832b65f0dce3a/romaja-lyrics/romaja_lyrics.js#L35) to see what I am talking about.

Just in case, to comment the whole function, you'll need to add a `/*` at the beginning of line 35, and a `*/` at the end on line 47. Result should be something like this:

![image](https://github.com/41pha1/spicetify-extensions/assets/9835489/cd820cb1-172f-48f5-94b1-089cbf01c264)

Apart from that, you'll need to comment the code in line 90 (as we can see [here](https://github.com/41pha1/spicetify-extensions/blob/e100b877408539fcaa4f8c7572c832b65f0dce3a/romaja-lyrics/romaja_lyrics.js#L90C13-L90C13)) by adding  a `//` at the beginning of the line.

Afterwards, you'll probably need to run `spicetify apply` to make Spicetify aware of the changes, and that should be all. I did this for the other extension, and it worked as expected.

Let me know if you have any questions or doubts.

---

@41pha1 : While reviewing this issue, the error message that was logged on console was about `Spicetify.Mousetrap()` not being a constructor.

Although I'm not familiar with how Spicetify works, I did take a look at both Spicetify's, as well to some built-in extensions' source code, and although I wasn't able to find anything that I could understand to implement a permanent fix, it seems that `Spicetify.Mousetrap()` needs to receive a document as parameter, as can be seen on keyboardShortcut.js [source code](https://github.com/spicetify/spicetify-cli/blob/aa624e65dc684d42f302107ad0571d61d67085cd/Extensions/keyboardShortcut.js#L153).

Just wanted to let you know in case that you can figure out what can be done.

Nonetheless, although I won't promise anything, I'll see if I can take a more detailed look at this.

Regards.

**Comment by antonio-gil** [comment]
@Lian16 glad to hear that the described workarounds worked for you!
