### ISSUE TITLE
For Lyric-Plus Issue

### ISSUE THREAD

**Issue by Arghadatta** [41pha1/spicetify-extensions#5]
@41pha1 as the lyric-plus fork of urs don't have issue tab for me to send there, i am doing it here.

in the synced and unsynced tab,the lyrics are for the song aren't coming.it gives another song's lyrics.

example:
THE LYRIC PAGE
![image](https://user-images.githubusercontent.com/78955676/199200110-ab8b32cf-b89a-4b15-80a0-c0725b741ceb.png)

it doesn't match the song's lyrics

**Comment by 41pha1** [comment]
Does this Problem with incorrect Lyrics still occur when you toggle the romaji conversion off?
If so I sadly have next to no impact on that because the lyrics are being fetched by the original lyrics-plus app. 
You could try opening this issue on the original Spotify-cli repo I forked.
This is sadly something I have also noticed in the past with lyrics-plus, this is why I will try to fix and clean up the extension to work for everyone as well!

**Comment by Arghadatta** [comment]
> Does this Problem with incorrect Lyrics still occur when you toggle the romaji conversion off? If so I sadly have next to no impact on that because the lyrics are being fetched by the original lyrics-plus app. You could try opening this issue on the original Spotify-cli repo I forked. This is sadly something I have also noticed in the past with lyrics-plus, this is why I will try to fix and clean up the extension to work for everyone as well!

After closing the conversion, ye it still mismatch. 

And replying the other text,i will issue it ig and always,thanks for ur help and quick reply on the matter.also good luck on the Project. 
Waiting when i can get my hands on the extension

**Comment by 41pha1** [comment]
Thanks for the kind comments!

The extension should already work right now, even installed via the marketplace, I changed the name and location though so you will have to reinstall it from marketplace and remove the manually  installed one with 

`spicetify config extensions romaji_lyrics.js-`
`spicetify apply`
